# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/cpu/proj_miniRV/proj_single_cycle/proj_single_cycle.srcs/sources_1/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/cpu/proj_miniRV/proj_single_cycle/proj_single_cycle.srcs/sources_1/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/cpu/proj_miniRV/proj_single_cycle/proj_single_cycle.srcs/sources_1/ip/IROM/IROM.xci
# IP: The module: 'IROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/cpu/proj_miniRV/proj_single_cycle/proj_single_cycle.srcs/sources_1/ip/IROM/IROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
