# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.cache/wt [current_project]
set_property parent.project_path E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/cpu/proj_miniRV/proj_pipeline/irom.coe
read_verilog E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/defines.vh
read_verilog -library xil_defaultlib {
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/ALU.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/Bridge.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/Ctrl.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/DATA_RISK.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/EX_MEM.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/ID_EX.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/IF_ID.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/MEM_WB.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/NPC.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/PC.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/RF.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/SEXT.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/STORE.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/button.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/counter.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/dig.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/led.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/myCPU.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/switch.v
  E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/new/miniRV_SoC.v
}
read_ip -quiet E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all e:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all e:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all e:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

read_ip -quiet E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/IROM/IROM.xci
set_property used_in_implementation false [get_files -all e:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/IROM/IROM_ooc.xdc]

read_ip -quiet E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/DRAM/DRAM.xci
set_property used_in_implementation false [get_files -all e:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/sources_1/ip/DRAM/DRAM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/constrs_1/new/miniRV_clock.xdc
set_property used_in_implementation false [get_files E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/constrs_1/new/miniRV_clock.xdc]

read_xdc E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/constrs_1/new/miniRV_SoC.xdc
set_property used_in_implementation false [get_files E:/cpu/proj_miniRV/proj_pipeline/proj_pipeline.srcs/constrs_1/new/miniRV_SoC.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top miniRV_SoC -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef miniRV_SoC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file miniRV_SoC_utilization_synth.rpt -pb miniRV_SoC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
